apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: test-agent-cluster-install
  namespace: spoke-cluster
spec:
  clusterDeploymentRef:
    name: single-node
  imageSetRef:
    name: openshift-${OCP_VER}
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    machineNetwork:
    - cidr: 192.168.111.0/24
    serviceNetwork:
    - 172.30.0.0/16
  provisionRequirements:
    controlPlaneAgents: ${MASTERS}
  sshPublicKey: |
    ${SSH_KEY}
