apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: myinfraenv
  namespace: spoke-cluster
spec:
  clusterRef:
    name: single-node         # Use the below created clusterDeployment resource name and namespace
    namespace: spoke-cluster
  pullSecretRef:
    name: pull-secret
  sshAuthorizedKey: '${SSH_KEY}'
